[package]
name = "july-fmt"
version = "0.1.0"
edition = "2024"

[dependencies]
julyc = { path = "../julyc" }
julyc-parse = { path = "../julyc-parse" }
julyc-arena = { path = "../julyc-arena" }
clap = { version = "4.5.31", features = ["derive"] }
