/// Definition of all kinds of tokens found within a source.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TokenKind {
    Const,
    Loop,
    If,
    Else,
    For,
    In,
    True,
    False,
    Break,
    Continue,
    Extern,
    Struct,
    Enum,
    Let,
    Fn,
    Ret,
    Semi,
    Colon,
    Equals,
    OpenParen,
    CloseParen,
    OpenBracket,
    CloseBracket,
    OpenCurly,
    CloseCurly,
    Int,
    Float,
    Str,
    Ident,
    Plus,
    Asterisk,
    Slash,
    Greater,
    Hyphen,
    Comma,
    Dot,
    DoubleDot,
    Pound,
    Ampersand,
    Bang,
    Caret,
    As,
}

impl TokenKind {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Extern => "extern",
            Self::Enum => "enum",
            Self::Struct => "struct",
            Self::Let => "let",
            Self::Fn => "fn",
            Self::Ret => "return",
            Self::Semi => ";",
            Self::Colon => ":",
            Self::Equals => "=",
            Self::OpenParen => "(",
            Self::CloseParen => ")",
            Self::OpenBracket => "[",
            Self::CloseBracket => "]",
            Self::OpenCurly => "{",
            Self::CloseCurly => "}",
            Self::Plus => "+",
            Self::Asterisk => "*",
            Self::Slash => "/",
            Self::Greater => ">",
            Self::Hyphen => "-",
            Self::Comma => ",",
            Self::Dot => ".",
            Self::DoubleDot => "..",
            Self::Pound => "#",
            Self::Ampersand => "&",
            Self::Bang => "!",
            Self::Caret => "^",
            Self::Const => "const",
            Self::Loop => "loop",
            Self::If => "if",
            Self::Else => "else",
            Self::For => "for",
            Self::In => "in",
            Self::True => "true",
            Self::False => "false",
            Self::Break => "break",
            Self::Continue => "continue",
            Self::Int => "integer",
            Self::Float => "float",
            Self::Str => "string",
            Self::Ident => "identifier",
            Self::As => "as",
        }
    }
}
