[package]
name = "pebble-fmt"
version = "0.1.0"
edition = "2024"

[dependencies]
pebblec = { path = "../pebblec" }
pebblec-parse = { path = "../pebblec-parse" }
pebblec-arena = { path = "../pebblec-arena" }
clap = { version = "4.5.31", features = ["derive"] }
